import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { renderDesign } from "./designer.js";
import type { WebSpec } from "./types.js";

export interface ScaffoldOptions {
  packageName?: string;
  force?: boolean;
}

export interface ScaffoldResult {
  outputDir: string;
  packageName: string;
  moduleName: string;
  command: string;
}

export async function scaffoldCli(spec: WebSpec, outputDir: string, options: ScaffoldOptions = {}): Promise<ScaffoldResult> {
  const root = resolve(outputDir);
  const slug = slugify(options.packageName ?? spec.name);
  const moduleName = slug.replaceAll("-", "_");
  await mkdir(`${root}/src`, { recursive: true });
  await mkdir(`${root}/skills/cli-anything-${slug}`, { recursive: true });
  await write(`${root}/package.json`, generatedPackageJson(slug));
  await write(`${root}/tsconfig.json`, generatedTsconfig());
  await write(`${root}/README.md`, generatedReadme(spec, slug));
  await write(`${root}/WEB2CLI.md`, renderDesign(spec));
  await write(`${root}/src/cli.ts`, generatedCli(spec, slug));
  await write(`${root}/src/spec.ts`, `import type { WebSpec } from "./types.js";\n\nexport const spec: WebSpec = ${JSON.stringify(spec, null, 2)};\n`);
  await write(`${root}/src/types.ts`, generatedTypes());
  await write(`${root}/skills/cli-anything-${slug}/SKILL.md`, generatedSkill(spec, slug));
  return {
    outputDir: root,
    packageName: `cli-anything-${slug}`,
    moduleName,
    command: `cli-anything-${slug}`
  };
}

function slugify(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "web-app";
}

async function write(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

function generatedPackageJson(slug: string): string {
  return `${JSON.stringify({
    name: `cli-anything-${slug}`,
    version: "0.1.0",
    type: "module",
    bin: { [`cli-anything-${slug}`]: "./dist/cli.js" },
    scripts: { build: "tsc -p tsconfig.json" },
    engines: { node: ">=20" },
    devDependencies: { "@types/node": "^24.0.0", "typescript": "^5.9.3" }
  }, null, 2)}\n`;
}

function generatedTsconfig(): string {
  return `${JSON.stringify({
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      skipLibCheck: true,
      outDir: "dist",
      rootDir: "src"
    },
    include: ["src/**/*.ts"]
  }, null, 2)}\n`;
}

function generatedReadme(spec: WebSpec, slug: string): string {
  return `# cli-anything-${slug}

Generated TypeScript CLI wrapper for \`${spec.target}\`.

\`\`\`bash
npm install
npm run build
npm link
cli-anything-${slug} --json status
cli-anything-${slug} api list
\`\`\`

The CLI exposes discovered routes, endpoint hints, form metadata, generic HTTP
helpers, and a small REPL.
`;
}

function generatedSkill(spec: WebSpec, slug: string): string {
  return `---
name: cli-anything-${slug}
description: Use this skill to operate the generated TypeScript CLI wrapper for ${spec.name}.
---

# cli-anything-${slug}

Use \`cli-anything-${slug} --json\` for parseable output.

\`\`\`bash
cli-anything-${slug} --json status
cli-anything-${slug} --json routes list
cli-anything-${slug} --json api list
cli-anything-${slug} request get /
\`\`\`
`;
}

function generatedTypes(): string {
  return `export interface RouteSpec {
  path: string;
  source: string;
  kind: "page" | "api";
  method: string;
  name?: string;
}

export interface ApiEndpointSpec {
  method: string;
  path: string;
  source: string;
  name?: string;
}

export interface FormFieldSpec {
  name: string;
  fieldType: string;
  required: boolean;
}

export interface FormSpec {
  action: string;
  method: string;
  source: string;
  fields: FormFieldSpec[];
  name?: string;
}

export interface WebSpec {
  target: string;
  targetType: "local" | "url";
  name: string;
  baseUrl?: string;
  frameworks: string[];
  packageScripts: Record<string, string>;
  routes: RouteSpec[];
  apiEndpoints: ApiEndpointSpec[];
  forms: FormSpec[];
  openapiFiles: string[];
  notes: string[];
}
`;
}

function generatedCli(spec: WebSpec, slug: string): string {
  return `#!/usr/bin/env node
// Generated by cli-anything-web2cli. Edit the spec first when possible.
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { spec } from "./spec.js";

let jsonOutput = false;
let baseUrl = spec.baseUrl;

function emit(data: unknown, message?: string): void {
  if (jsonOutput) {
    console.log(JSON.stringify(data, null, 2));
    return;
  }
  if (message) console.log(message);
  if (typeof data === "string") console.log(data);
  else console.log(JSON.stringify(data, null, 2));
}

function fail(message: string): never {
  if (jsonOutput) console.log(JSON.stringify({ error: message }));
  else console.error(\`Error: \${message}\`);
  process.exit(1);
}

function resolveUrl(path: string): string {
  if (path.startsWith("http://") || path.startsWith("https://")) return path;
  if (!baseUrl) fail("No base URL is known. Pass --base-url or use an absolute URL.");
  return new URL(path.replace(/^\\/+/, ""), baseUrl.endsWith("/") ? baseUrl : \`\${baseUrl}/\`).toString();
}

async function request(method: string, path: string, body?: string): Promise<unknown> {
  const response = await fetch(resolveUrl(path), {
    method,
    headers: { "user-agent": "cli-anything-${slug}/0.1" },
    body
  });
  const text = await response.text();
  let parsed: unknown = text;
  if ((response.headers.get("content-type") ?? "").includes("json") || /^[{[]/.test(text)) {
    try { parsed = JSON.parse(text); } catch {}
  }
  return { status: response.status, ok: response.ok, url: response.url, body: parsed };
}

async function run(argv: string[]): Promise<void> {
  const args = [...argv];
  while (args[0]?.startsWith("--")) {
    const flag = args.shift();
    if (flag === "--json") jsonOutput = true;
    else if (flag === "--base-url") baseUrl = args.shift();
    else if (flag === "--help" || flag === "-h") return help();
    else fail(\`Unknown option: \${flag}\`);
  }
  const command = args.shift();
  if (!command) return repl();
  if (command === "status") return emit({
    name: spec.name,
    target: spec.target,
    targetType: spec.targetType,
    baseUrl,
    frameworks: spec.frameworks,
    routeCount: spec.routes.length,
    apiCount: spec.apiEndpoints.length,
    formCount: spec.forms.length,
    notes: spec.notes
  });
  if (command === "routes" && args[0] === "list") return emit(spec.routes);
  if (command === "api" && args[0] === "list") return emit(spec.apiEndpoints);
  if (command === "api" && args[0] === "call") {
    const [, method, path, ...rest] = args;
    const bodyIndex = rest.indexOf("--body");
    const body = bodyIndex >= 0 ? rest[bodyIndex + 1] : undefined;
    return emit(await request(method ?? "GET", path ?? "/", body));
  }
  if (command === "forms" && args[0] === "list") return emit(spec.forms);
  if (command === "request" && args[0] === "get") return emit(await request("GET", args[1] ?? "/"));
  if (command === "request" && args[0] === "post") {
    const bodyIndex = args.indexOf("--body");
    return emit(await request("POST", args[1] ?? "/", bodyIndex >= 0 ? args[bodyIndex + 1] : ""));
  }
  if (command === "repl") return repl();
  fail(\`Unknown command: \${command}\`);
}

function help(): void {
  console.log(\`cli-anything-${slug}

Commands:
  status
  routes list
  api list
  api call <method> <path> [--body json]
  forms list
  request get <path>
  request post <path> [--body json]
\`);
}

async function repl(): Promise<void> {
  const rl = createInterface({ input, output });
  console.log("cli-anything-${slug}> type help or quit");
  for (;;) {
    const line = (await rl.question("> ")).trim();
    if (!line) continue;
    if (line === "quit" || line === "exit") break;
    if (line === "help") {
      help();
      continue;
    }
    await run(line.split(/\\s+/));
  }
  rl.close();
}

run(process.argv.slice(2)).catch((error) => fail(error instanceof Error ? error.message : String(error)));
`;
}
